# permissions for end users to view transporturls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: transporturl-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: infra-operator
    app.kubernetes.io/part-of: infra-operator
    app.kubernetes.io/managed-by: kustomize
  name: transporturl-viewer-role
rules:
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rabbitmq.openstack.org
  resources:
  - transporturls/status
  verbs:
  - get
